# version: '2'
# services:
#   zookeeper:
#     image: wurstmeister/zookeeper
#     ports:
#     - "2181:2181"

#   kafka:
#     image: wurstmeister/kafka
#     ports:
#       - "9092:9092"

#     environment:
#       # kafka가 클라이언트에게 이 주소로 접속해달라고 알리는 정보가 필요
#       # INSIDE : 9093, OUTSIDE : 9092
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093, OUTSIDE://localhost:9092

#       # 각 서비스의 통신 방식을 지정(암호화지정 여부)
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      
#       # kafka가 실제 통신해서 듣고 있는 주소 정보 
#       # 포트포워드 느낌
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093, OUTSIDE://localhost:9092

#       # zookeeper 클러스터와 연결
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#       # kafka server - broker - Client 간에 사용할 리스너 정보 
#       # 내부통신(inside)
#       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      # kafka가 클라이언트에게 이 주소로 접속해줘라고 알리는 정보
      # INSIDE : 9093, OUTSIDE : 9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093, OUTSIDE://localhost:9092 

      # 각 서비스의 통신방식을 지정(암호화지정 여부)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT

      # kafak가 실제 통신해서 듣고 있는 주소 정보 
      # 
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093, OUTSIDE://0.0.0.0:9092 

      # zookeeper 클러스터와 연결 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      # kafka server - broker - client 사용할 리스너정보 
      # 내부통신(inside) 
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
