# # local host
# server:
#     # 0 : eureka server 의해서 임의 포트가 할당됨(spring server)
#     port: 0
    
# spring :
    
#     application:
#         # api gateway
#         # http://server.xxxx.shop/
#         # url pattern
#         # http://server.xxxx.shop/product-service/
#         # http://server.xxxx.shop/product-service/product/create
#         name: product-service

#     # mariadb 설정        
#     datasource:
#         driver-class-name: org.mariadb.jdbc.Driver
#         url: jdbc:mariadb://localhost:3306/inspire
#         username: root
#         password: 123456789
    
#     jpa:
#       hibernate: 
#         # create, create-drop, update, none create하면 서버재기동할 때마다 새로 테이블 만들어지면서 데이터 날라감, 한 번 만들고 나면 none으로 바꾸기
#         ddl-auto: create
#       # 콘솔출력
#       show-sql: true  
#       properties:
#         hibernate:
#           # h2
#           # dialect: org.hibernate.dialect.H2Dialect
#           # mariadb
#           dialect: org.hibernate.dialect.MariaDBDialect
#           format_sql: true

#     #redis
#     #docker run -d --name redis-container -p 6379:6379 redis:7.2
#     #docker exec -it redis-container redis-cli
#     #ping
#     #docker run -d --name redis-insight -p 8001:5540 reids/redisinsight:latest
#     #http://localhost:8001
#     #Host: redis 또는 host.docker.internal , port: 6379

#     # data:
#     #     redis:
#     #         host: localhost
#     #         port: 6379
#     #         password:
#     #         timeout: 6000ms

#     kafka:
#         kafka-server: localhost:9092
#         consumer:
#             group-id: product-group
#             auto-offset-reset: earliest

# # eureka client user service -> eureka server
# eureka:
#     client:
#         serviceUrl:
#             defaultZone: http://localhost:8761/eureka




# msa - k8s - aws version
# eks 배포시 eureka server에 등록하지 않겠다는 의미 
eureka:
  client:
    enabled: false

spring :
    application:
      name: product-service

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://${DB_HOST}:3306/inspire?useSSL=true&requireSSL=true  
      username: ${DB_ADMIN}  
      password: ${DB_PASSWORD}

    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MariaDBDialect
      generate-ddl: true
      hibernate:
        ddl-auto: create
      show-sql: true

    kafka:
      # pod 실행중인 service 이름으로 변경 (localhost X)
      kafka-server: kafka-service:9092
      consumer:
        group-id: product-group
        auto-offset-reset: earliest