apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: lgcns

spec: 
  # 자원공간의 낭비를 방지하고 관리의 편리성을 
  revisionHistoryLimit: 2

  replicas: 1
  selector:
    matchLabels:
      app: product
  
  template:
    metadata:
      labels:
        app: product
    
    spec:
      # docker container
      containers:
        - name: product-container
          # ecr 경로 
          image: 447839931800.dkr.ecr.us-west-2.amazonaws.com/product-service:latest
          ports:
          - containerPort: 8080
          resources:
            # 컨테이너가 사용할 수 있는 최대치의 리소스
            limits:
              cpu: "1"
              memory: "500Mi"
            # 컨테이너가 기동할 때 보장 받는 최소 리소스
            requests:
              cpu: "0.5"
              memory: "500Mi"
          # secret 작성 후 외부환경변수를 이용해서 파드 실행시 주입할 예정
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_HOST
          
          - name: DB_ADMIN
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_ADMIN
          
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lgcns-app-secrets
                key: DB_PASSWORD

          # 컨테이너 상태 확인, browser를 통해서가 아닌 pod에 직접 접근하는 방법
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080


---
# core service setting
# core group : pod, service, ConfigMap, Secret, namespace
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: lgcns

spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: product



