name: deploy order

on:
  push:
    branches:
      - main

jobs:

  # job name
  build-and-deploy:
    
    #runner
    runs-on: ubuntu-latest

    #step에서 사용하는 명령어 볼 수 있는 사이트 https://docs.github.com/ko/actions
    steps:
      # 소스코드 check out
      - name: checkout github
        uses: actions/checkout@v2

      # 리눅스 환경에서 kubectl client 설치
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.34.1"
      
      # git 레포마다 secret 설정이 달라짐, aws 인증 
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET}}
          aws-region: us-west-2

      - name: aws eks cluster update
        run: aws eks update-kubeconfig --region us-west-2 --name lgcns-syjeong-cluster

      - name: aws ecr login
        uses: aws-actions/amazon-ecr-login@v1 
      
      # infra 구축(ingress, kafka, redis, zookeeper, rabbitMQ)
      - name: deploy infra
        run: | 
          kubectl apply -f ./k8s/msa_ingress.yml
          kubectl apply -f ./k8s/msa_zookeeper.yml
          kubectl apply -f ./k8s/msa_kafka.yml
          kubectl apply -f ./k8s/msa_redis.yml
      
      # image 생성하고 ecr push까지 자동화
      # apigateway, user, product, order
      # git 레포를 root로 보고 경로 설정 
      - name: apigateway image build and push docker image to ecr
        env:
          REGISTRY: 447839931800.dkr.ecr.us-west-2.amazonaws.com
          REPOSITORY: apigateway
          IMAGE_TAG: latest
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./apigateway/Dockerfile ./apigateway
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
      - name: eks kubectl apigateway apply
        run: |
          kubectl apply -f ./apigateway/k8s/apigateway-depl.yml
          kubectl rollout restart deployment apigateway-deployment -n lgcns

      - name: user image build and push docker image to ecr
        env:
          REGISTRY: 447839931800.dkr.ecr.us-west-2.amazonaws.com
          REPOSITORY: user
          IMAGE_TAG: latest
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./user/Dockerfile ./user
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
      - name: eks kubectl user apply
        run: |
          kubectl apply -f ./user/k8s/user-depl.yml
          kubectl rollout restart deployment user-deployment -n lgcns     